GRANT USAGE ON SCHEMA public TO :user_name;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO :user_name;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO :user_name;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA PUBLIC TO :user_name;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT EXECUTE ON FUNCTIONS TO :user_name;
